blank_issues_enabled: false
contact_links:
  - name: Questions and help
    url: https://discord.gg/ky3tyJJaJA
    about: Ask on the DankMinecraftServers Discord.
  - name: Get listed on DankMinecraftServers
    url: https://dankminecraftservers.com
    about: List your server and get vote traffic.
